listener:
  package_name: fbot_bringup
  executable: listener.launch.py
  enable: 'true'
  parameters:
    name: 'listener'
    namespace: 'listeningg'

talker:
  package_name: fbot_bringup
  executable: talker.launch.py
  enable: 'true'
  parameters:
    name: 'talker123'
    namespace: 'talking'
    
talker1:
  package_name: fbot_bringup
  executable: talker.launch.py
  enable: 'true'
  parameters:
    name: 'talker1'
    namespace: 'talking11'
